# Individual Project 5
### Author: Carmen Gasco Galvez
Version: 1.20.3, 
Spring semester

1. Set up the Self-awareness dataset at least 65 entries. You will need to create models to predict the end of the day feeling.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
dataset=pd.read_excel('SAdataset.xlsx')

In [3]:
dataset.head()

Date        Day  Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  \
0  14-ene     Friday         7.0            0.0         2.5           0.5   
1  15-ene   Saturday         6.0            1.5         1.0           0.0   
2  16-ene     Sunday         7.0            0.0         0.0           0.0   
3  17-ene     Monday         6.0            0.0         6.2           0.0   
4  19-ene  Wednesday         7.0            0.0         1.5           1.0   

   Work Hour  End of the day Feeling (0 to 10)  
0          0                                 4  
1          0                                 2  
2          0                                 1  
3          0                                 0  
4          0                                 1

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Date                              60 non-null     object 
 1   Day                               60 non-null     object 
 2   Sleep Hour                        60 non-null     float64
 3   Exercise Hour                     60 non-null     float64
 4   Study Hour                        60 non-null     float64
 5   StudyDS Hour                      60 non-null     float64
 6   Work Hour                         60 non-null     int64  
 7   End of the day Feeling (0 to 10)  60 non-null     int64  
dtypes: float64(4), int64(2), object(2)
memory usage: 3.9+ KB


In [5]:
dataset.isnull().sum()

Date                                0
Day                                 0
Sleep Hour                          0
Exercise Hour                       0
Study Hour                          0
StudyDS Hour                        0
Work Hour                           0
End of the day Feeling (0 to 10)    0
dtype: int64



There are no missing values, so it is not necessary to see the distribution of the data

2. Split your dataset into 48 entries for training, 12 entries for testing and 5 entries for validation.

In [6]:
dataset.columns

Index(['Date', 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour', 'End of the day Feeling (0 to 10)'],
      dtype='object')

In [7]:
X=dataset[['Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour']]
y=dataset[['End of the day Feeling (0 to 10)']]

In [8]:
X=pd.get_dummies(dataset[[ 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour']], drop_first=True)

In [9]:
X.head()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  Day_Monday  \
0         7.0            0.0         2.5           0.5          0           0   
1         6.0            1.5         1.0           0.0          0           0   
2         7.0            0.0         0.0           0.0          0           0   
3         6.0            0.0         6.2           0.0          0           1   
4         7.0            0.0         1.5           1.0          0           0   

   Day_Saturday  Day_Sunday  Day_Thursday  Day_Tuesday  Day_Wednesday  
0             0           0             0            0              0  
1             1           0             0            0              0  
2             0           1             0            0              0  
3             0           0             0            0              0  
4             0           0             0            0              1

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=42)

Now I train my model

In [11]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

Intercept and coefficeints

In [12]:
print("Coefficients",regressor.coef_)
print("Intercept",regressor.intercept_)

Coefficients [[-5.87534219e-02  7.27765899e-02  3.33045130e-02  3.39337669e-02
   1.38777878e-17 -1.71977842e-01  3.71033166e-01 -1.54651570e-01
  -1.18060166e-01 -2.86180467e-01 -6.81690800e-02]]
Intercept [1.92027358]


Predicting the Test set results 

In [13]:
y_pred=regressor.predict(X_test)

Validation

In [14]:
X.head()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour  Day_Monday  \
0         7.0            0.0         2.5           0.5          0           0   
1         6.0            1.5         1.0           0.0          0           0   
2         7.0            0.0         0.0           0.0          0           0   
3         6.0            0.0         6.2           0.0          0           1   
4         7.0            0.0         1.5           1.0          0           0   

   Day_Saturday  Day_Sunday  Day_Thursday  Day_Tuesday  Day_Wednesday  
0             0           0             0            0              0  
1             1           0             0            0              0  
2             0           1             0            0              0  
3             0           0             0            0              0  
4             0           0             0            0              1

Tuesday, sleep 6.5, exercise 0.5, study 2.8, study DS 0, Work 0, Feeling 0

In [15]:
regressor.predict([[6.5, 0.5, 2.8, 0,0,0,0,0,0,1 ,0]])

array([[1.3818368]])

Thursday, sleep 7, exercise 1.5, study 3.5, study DS 0, Work 0, Feeling 1

In [16]:
regressor.predict([[7, 1.5, 3.5, 0,0,0,0,0,1,0 ,0]])

array([[1.61667014]])

Monday, sleep 5, exercise 0, study 5, study DS 0, Work 0, Feeling 2

In [17]:
regressor.predict([[5, 0, 5, 0,0,1,0,0,0,0 ,0]])

array([[1.62105119]])

Thursday, sleep 5.5, exercise 1, study 0, study DS 0, Work 0, Feeling 3

In [18]:
regressor.predict([[5.5, 1, 0, 0,0,0,0,0,1,0 ,0]])

array([[1.55184618]])

Monday, sleep 6.5, exercise 0, study 0, study DS 0, Work 0, Feeling 2

In [19]:
regressor.predict([[6.5, 0, 0, 0,0,1,0,0,0,0 ,0]])

array([[1.36639849]])

In [20]:
from sklearn.metrics import r2_score
print('R-Square', r2_score(y_test,y_pred))

R-Square 0.06703045585846656


In [23]:
import statsmodels.api as sm
X=sm.add_constant(X)

In [24]:
model=sm.OLS(y,X).fit()

In [25]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                   OLS Regression Results                                   
============================================================================================
Dep. Variable:     End of the day Feeling (0 to 10)   R-squared:                       0.098
Model:                                          OLS   Adj. R-squared:                 -0.086
Method:                               Least Squares   F-statistic:                    0.5325
Date:                              Sun, 20 Mar 2022   Prob (F-statistic):              0.859
Time:                                      00:51:51   Log-Likelihood:                -80.843
No. Observations:                                60   AIC:                             183.7
Df Residuals:                                    49   BIC:                             206.7
Df Model:                                        10                                         
Covariance Type:                          nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             2.0931      1.653      1.266      0.211      -1.229       5.415
Sleep Hour       -0.0282      0.249     -0.113      0.910      -0.528       0.472
Exercise Hour     0.0068      0.242      0.028      0.978      -0.479       0.492
Study Hour        0.0445      0.077      0.575      0.568      -0.111       0.200
StudyDS Hour      0.0203      0.190      0.107      0.916      -0.362       0.403
Work Hour      2.185e-16   4.34e-16      0.503      0.617   -6.54e-16    1.09e-15
Day_Monday       -0.7392      0.544     -1.359      0.180      -1.832       0.354
Day_Saturday      0.1126      0.466      0.242      0.810      -0.823       1.048
Day_Sunday       -0.5591      0.476     -1.175      0.246      -1.516       0.397
Day_Thursday     -0.4243      0.521     -0.815      0.419      -1.471       0.622
Day_Tuesday      -0.5681      0.514     -1.105      0.275      -1.601       0.465
Day_Wednesday    -0.5853      0.485     -1.207      0.233      -1.560       0.389
==============================================================================
Omnibus:                        1.761   Durbin-Watson:                   1.164
Prob(Omnibus):                  0.415   Jarque-Bera (JB):                1.279
Skew:                           0.104   Prob(JB):                        0.527
Kurtosis:                       2.316   Cond. No.                     1.87e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.14e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""